# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""End-to-end tests for the full nftables ruleset generation.

Each test builds a small firewall configuration in an isolated in-memory
database and asserts the text emitted by ``compiler.compile_ruleset``.
One test per firewall feature (zones, address/service groups, IP
families, rate limit, logging, NAT in every mode, the DNAT lock-out
safety net, the WireGuard auto rules, ordering and the enabled filter) so
a regression in the security-critical ruleset is caught in CI rather than
on a production box.

The session is a fresh ``sqlite://`` engine per test, isolated from the
application database and from the other test modules.
"""
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from app import models
from app.compiler import compile_ruleset


@pytest.fixture()
def session():
    engine = create_engine("sqlite://")
    models.Base.metadata.create_all(engine)
    with Session(engine) as s:
        yield s


def _zone(s, name, *iface_names):
    z = models.Zone(name=name)
    s.add(z)
    s.flush()
    for n in iface_names:
        s.add(models.Interface(name=n, zone_id=z.id, type="physical", enabled=True))
    s.flush()
    return z


def _add_rule(s, **kw):
    kw.setdefault("chain", "forward")
    kw.setdefault("enabled", True)
    r = models.FirewallRule(**kw)
    s.add(r)
    s.flush()
    return r


def _iface(s, name, ip=None):
    i = models.Interface(name=name, type="physical", enabled=True,
                         ip_mode="static" if ip else "none", ip_address=ip)
    s.add(i)
    s.flush()
    return i


def test_empty_ruleset_has_tables_chains_and_policies(session):
    out = compile_ruleset(session)
    assert "#!/usr/sbin/nft -f" in out
    assert "table inet filter {" in out
    assert "table ip nat {" in out
    assert "type filter hook input priority filter; policy drop;" in out
    assert "type filter hook forward priority filter; policy drop;" in out
    assert "type filter hook output priority filter; policy accept;" in out
    assert "type nat hook prerouting priority dstnat;" in out
    assert "type nat hook postrouting priority srcnat;" in out


def test_baseline_stateful_lines_present(session):
    out = compile_ruleset(session)
    assert "iif lo accept" in out
    assert "ct state established,related accept" in out
    assert "ct state invalid drop" in out
    assert out.count("ip6 nexthdr icmpv6 accept") == 2


def test_header_is_english(session):
    assert "# Generated by MurOS - do not edit manually" in compile_ruleset(session)


def test_zone_rule_uses_interface_names(session):
    _zone(session, "lan", "eth1")
    lan = session.query(models.Zone).filter_by(name="lan").one()
    r = _add_rule(session, action="accept", src_zone_id=lan.id, protocol="tcp", dst_port="80")
    out = compile_ruleset(session)
    assert "iifname eth1" in out
    assert "tcp dport 80" in out
    assert f"[muros r={r.id}]" in out


def test_multi_interface_zone_builds_set(session):
    _zone(session, "lan", "eth1", "eth2")
    lan = session.query(models.Zone).filter_by(name="lan").one()
    _add_rule(session, action="accept", src_zone_id=lan.id)
    out = compile_ruleset(session)
    assert "iifname { eth1, eth2 }" in out


def test_dst_zone_uses_oifname(session):
    _zone(session, "wan", "eth0")
    wan = session.query(models.Zone).filter_by(name="wan").one()
    _add_rule(session, action="accept", dst_zone_id=wan.id)
    out = compile_ruleset(session)
    assert "oifname eth0" in out


def test_empty_zone_guard_emits_no_rule(session):
    z = models.Zone(name="empty")
    session.add(z)
    session.flush()
    r = _add_rule(session, action="accept", src_zone_id=z.id)
    out = compile_ruleset(session)
    assert f"[muros r={r.id}]" not in out


def test_ipv4_address_uses_ip_keyword(session):
    r = _add_rule(session, action="accept", src_address="10.0.0.0/24")
    out = compile_ruleset(session)
    assert "ip saddr 10.0.0.0/24" in out
    assert f"[muros r={r.id}]" in out


def test_ipv6_address_uses_ip6_keyword(session):
    _add_rule(session, action="accept", dst_address="2001:db8::/32")
    out = compile_ruleset(session)
    assert "ip6 daddr 2001:db8::/32" in out


def test_address_group_splits_by_family(session):
    g = models.AddressGroup(name="mixed")
    g.entries = [
        models.AddressGroupEntry(value="10.0.0.0/24"),
        models.AddressGroupEntry(value="2001:db8::/32"),
    ]
    session.add(g)
    session.flush()
    _add_rule(session, action="accept", dst_address_group_id=g.id)
    out = compile_ruleset(session)
    assert "ip daddr 10.0.0.0/24" in out
    assert "ip6 daddr 2001:db8::/32" in out


def test_address_group_multiple_v4_builds_set(session):
    g = models.AddressGroup(name="admins")
    g.entries = [
        models.AddressGroupEntry(value="10.0.0.0/24"),
        models.AddressGroupEntry(value="192.168.10.0/24"),
    ]
    session.add(g)
    session.flush()
    _add_rule(session, action="accept", src_address_group_id=g.id)
    out = compile_ruleset(session)
    assert "ip saddr { 10.0.0.0/24, 192.168.10.0/24 }" in out


def test_icmp_rule_covers_both_families(session):
    _add_rule(session, action="accept", protocol="icmp")
    out = compile_ruleset(session)
    assert "meta l4proto { icmp, ipv6-icmp }" in out


def test_portless_tcp_rule_matches_both_families(session):
    _add_rule(session, action="accept", protocol="tcp")
    out = compile_ruleset(session)
    assert "meta l4proto tcp" in out
    assert "ip protocol tcp" not in out


def test_service_group_multi_protocol_yields_one_line_each(session):
    sg = models.ServiceGroup(name="kerberos")
    sg.ports = [
        models.ServiceGroupPort(protocol="tcp", port="88"),
        models.ServiceGroupPort(protocol="udp", port="88"),
    ]
    session.add(sg)
    session.flush()
    _add_rule(session, action="accept", service_group_id=sg.id)
    out = compile_ruleset(session)
    assert "tcp dport 88" in out
    assert "udp dport 88" in out


def test_rate_limit_is_emitted(session):
    _add_rule(session, action="accept", protocol="tcp", dst_port="22",
              rate_limit="5/minute burst 10")
    out = compile_ruleset(session)
    assert "limit rate 5/minute burst 10 packets" in out


def test_logging_prefix_carries_action_and_rule_id(session):
    r = _add_rule(session, chain="input", action="drop", protocol="tcp",
                  dst_port="23", log=True)
    out = compile_ruleset(session)
    assert f'log prefix "[muros DROP r={r.id} input] "' in out


def test_every_rule_has_counter_and_marker_comment(session):
    r = _add_rule(session, action="accept")
    out = compile_ruleset(session)
    line = next(ln for ln in out.splitlines() if f"[muros r={r.id}]" in ln)
    assert "counter" in line
    assert line.strip().endswith(f'comment "[muros r={r.id}]"')


def test_disabled_rule_is_skipped(session):
    r = _add_rule(session, action="accept", protocol="tcp", dst_port="9999",
                  enabled=False)
    out = compile_ruleset(session)
    assert f"[muros r={r.id}]" not in out
    assert "dport 9999" not in out


def test_rules_are_ordered_by_position(session):
    first = _add_rule(session, action="accept", protocol="tcp", dst_port="111",
                      position=1)
    second = _add_rule(session, action="accept", protocol="tcp", dst_port="222",
                       position=2)
    out = compile_ruleset(session)
    assert out.index(f"[muros r={first.id}]") < out.index(f"[muros r={second.id}]")


def test_nat_masquerade(session):
    eth0 = _iface(session, "eth0")
    n = models.NatRule(type="masquerade", interface_id=eth0.id, enabled=True)
    session.add(n)
    session.flush()
    out = compile_ruleset(session)
    assert "oifname eth0" in out
    assert "masquerade" in out
    assert f"[muros nat={n.id}]" in out


def test_nat_snat_to_explicit_ip(session):
    eth0 = _iface(session, "eth0")
    n = models.NatRule(type="snat", interface_id=eth0.id,
                       redirect_to_ip="203.0.113.9", enabled=True)
    session.add(n)
    session.flush()
    out = compile_ruleset(session)
    assert "snat to 203.0.113.9" in out


def test_nat_dnat_with_explicit_destination(session):
    eth0 = _iface(session, "eth0")
    n = models.NatRule(type="dnat", interface_id=eth0.id,
                       dst_address="203.0.113.1", protocol="tcp", dst_port="443",
                       redirect_to_ip="10.0.0.5", redirect_to_port="8443",
                       enabled=True)
    session.add(n)
    session.flush()
    out = compile_ruleset(session)
    assert "ip daddr 203.0.113.1" in out
    assert "tcp dport 443" in out
    assert "dnat to 10.0.0.5:8443" in out


def test_nat_dnat_without_destination_excludes_firewall_ips(session):
    _iface(session, "eth1", ip="192.168.1.1/24")
    eth0 = _iface(session, "eth0")
    n = models.NatRule(type="dnat", interface_id=eth0.id, protocol="tcp",
                       dst_port="443", redirect_to_ip="10.0.0.5", enabled=True)
    session.add(n)
    session.flush()
    out = compile_ruleset(session)
    assert "ip daddr != 192.168.1.1" in out
    assert "dnat to 10.0.0.5" in out


def test_disabled_nat_rule_is_skipped(session):
    eth0 = _iface(session, "eth0")
    n = models.NatRule(type="masquerade", interface_id=eth0.id, enabled=False)
    session.add(n)
    session.flush()
    out = compile_ruleset(session)
    assert f"[muros nat={n.id}]" not in out


def test_wireguard_disabled_adds_nothing(session):
    session.add(models.WireGuardConfig(id=1, enabled=False,
                                       interface_name="wg0",
                                       address_cidr="10.10.0.1/24"))
    session.flush()
    out = compile_ruleset(session)
    assert "wg0" not in out


def test_wireguard_enabled_adds_forward_and_masquerade(session):
    session.add(models.WireGuardConfig(id=1, enabled=True,
                                       interface_name="wg0",
                                       address_cidr="10.10.0.1/24"))
    session.flush()
    out = compile_ruleset(session)
    assert 'iifname "wg0" accept' in out
    assert 'oifname "wg0" accept' in out
    assert "tcp option maxseg size set rt mtu" in out
    assert 'ip saddr 10.10.0.0/24 oifname != "wg0" masquerade' in out
