# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""Unit tests for the nginx management-vhost renderer.

Pure tests: render_site_conf takes a config object and returns the
sites-available/muros text, no nginx and no filesystem involved.
"""
from types import SimpleNamespace

from app.nginx_config import render_site_conf


def _cfg(**kw):
    defaults = dict(listen_address="0.0.0.0", port_https=443, port_http=80,
                    redirect_http_to_https=True)
    defaults.update(kw)
    return SimpleNamespace(**defaults)


def test_header_and_tls_block_present():
    out = render_site_conf(_cfg())
    assert out.startswith("# Generated by MurOS - do not edit by hand.")
    assert "ssl_certificate     /etc/nginx/ssl/muros.crt;" in out
    assert "ssl_protocols       TLSv1.2 TLSv1.3;" in out
    assert 'Strict-Transport-Security "max-age=31536000" always;' in out


def test_security_headers_and_api_proxy():
    out = render_site_conf(_cfg())
    assert "add_header X-Frame-Options DENY always;" in out
    assert "add_header X-Content-Type-Options nosniff always;" in out
    assert "proxy_pass         http://127.0.0.1:8000;" in out
    assert "location / { try_files $uri $uri/ /index.html; }" in out


def test_wildcard_listen_uses_default_server_and_http2():
    out = render_site_conf(_cfg(listen_address="0.0.0.0"))
    assert "listen 443 ssl default_server;" in out
    assert "listen [::]:443 ssl default_server;" in out
    assert "http2 on;" in out


def test_specific_listen_address_is_scoped():
    out = render_site_conf(_cfg(listen_address="192.168.1.1"))
    assert "listen 192.168.1.1:443 ssl;" in out
    assert "default_server" not in out


def test_redirect_enabled_emits_301():
    out = render_site_conf(_cfg(redirect_http_to_https=True))
    assert "return 301 https://$host$request_uri;" in out


def test_redirect_disabled_serves_ui_over_http():
    out = render_site_conf(_cfg(redirect_http_to_https=False))
    assert "return 301 https://$host$request_uri;" not in out
    # Both server blocks then serve the SPA root.
    assert out.count("root /opt/muros/web;") == 2


def test_custom_ports_are_honored():
    out = render_site_conf(_cfg(listen_address="10.0.0.1", port_https=8443, port_http=8080))
    assert "listen 10.0.0.1:8443 ssl;" in out
    assert "listen 10.0.0.1:8080;" in out
