# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""Unit tests for the sshd drop-in renderer and authorized_keys parsing.

Pure tests: render_dropin and the key helpers take plain data and return
strings/dicts, so no sshd, no filesystem and no system call is involved.
"""
import base64
import hashlib
from types import SimpleNamespace

from app import ssh_config


def _cfg(**kw):
    defaults = dict(
        port=22, listen_address="0.0.0.0",
        permit_root_login="prohibit-password",
        password_authentication=False, pubkey_authentication=True,
        max_auth_tries=3, client_alive_interval=300, client_alive_count_max=2,
    )
    defaults.update(kw)
    return SimpleNamespace(**defaults)


def test_render_has_header_and_core_settings():
    out = ssh_config.render_dropin(_cfg())
    assert out.startswith("# Generated by MurOS")
    assert "Port 22" in out
    assert "PermitRootLogin prohibit-password" in out
    assert "PasswordAuthentication no" in out
    assert "PubkeyAuthentication yes" in out
    assert "MaxAuthTries 3" in out


def test_render_always_emits_hardening_lines():
    out = ssh_config.render_dropin(_cfg())
    for line in (
        "X11Forwarding no", "PermitEmptyPasswords no", "UsePAM yes",
        "KbdInteractiveAuthentication no", "AllowAgentForwarding no",
        "AllowTcpForwarding no",
    ):
        assert line in out


def test_render_omits_listen_address_for_wildcard():
    assert "ListenAddress" not in ssh_config.render_dropin(_cfg(listen_address="0.0.0.0"))


def test_render_includes_specific_listen_address():
    out = ssh_config.render_dropin(_cfg(listen_address="192.168.1.1"))
    assert "ListenAddress 192.168.1.1" in out


def test_render_password_auth_can_be_enabled():
    out = ssh_config.render_dropin(_cfg(password_authentication=True))
    assert "PasswordAuthentication yes" in out


def test_parse_valid_key_with_comment():
    b64 = base64.b64encode(b"\x00\x00\x00\x0bssh-ed25519-body").decode()
    parsed = ssh_config._parse_authorized_key_line(f"ssh-ed25519 {b64} alice@laptop")
    assert parsed["type"] == "ssh-ed25519"
    assert parsed["key_b64"] == b64
    assert parsed["comment"] == "alice@laptop"
    assert parsed["fingerprint"].startswith("SHA256:")


def test_parse_key_without_comment():
    parsed = ssh_config._parse_authorized_key_line("ssh-ed25519 QUJDRA==")
    assert parsed is not None
    assert parsed["comment"] == ""


def test_parse_rejects_unknown_key_type():
    assert ssh_config._parse_authorized_key_line("foo-bar QUJDRA== x") is None


def test_parse_rejects_invalid_base64():
    assert ssh_config._parse_authorized_key_line("ssh-ed25519 not!valid!base64 x") is None


def test_parse_ignores_comments_and_blank_lines():
    assert ssh_config._parse_authorized_key_line("# a comment") is None
    assert ssh_config._parse_authorized_key_line("   ") is None


def test_fingerprint_matches_sha256_of_decoded_key():
    b64 = "QUJDRA=="  # decodes to b"ABCD"
    expected = "SHA256:" + base64.b64encode(
        hashlib.sha256(b"ABCD").digest()).decode().rstrip("=")
    assert ssh_config._compute_fingerprint("ssh-ed25519", b64) == expected


def test_fingerprint_empty_on_bad_base64():
    assert ssh_config._compute_fingerprint("ssh-ed25519", "not!base64") == ""
