# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""IPv6 Router Advertisements (radvd) generation and apply.

radvd makes the firewall the IPv6 router for a LAN interface: it sends
Router Advertisements so clients SLAAC-autoconfigure an address and a
default route. The advertised /64 is derived from the interface's own
IPv6 address. This is the IPv6 counterpart of the (IPv4-only) DHCP server.
radvd needs IPv6 forwarding enabled, which apply() turns on when the
feature is on.
"""
from __future__ import annotations

import ipaddress
import logging
import os
import subprocess
from pathlib import Path

from sqlalchemy.orm import Session

from app import models

log = logging.getLogger("muros.ra")

MUROS_RADVD_CONF = Path(os.environ.get("MUROS_RADVD_CONF", "/etc/radvd.conf"))
APPLY = os.environ.get("MUROS_APPLY", "").lower() in ("1", "true", "yes")


def get_config(db: Session) -> models.RaConfig:
    cfg = db.get(models.RaConfig, 1)
    if cfg is None:
        cfg = models.RaConfig(id=1)
        db.add(cfg)
        db.commit()
    return cfg


def _iface_v6_prefix(db: Session, iface_name: str | None) -> str | None:
    """Return the /64 prefix advertised on iface, from its IPv6 address."""
    if not iface_name:
        return None
    itf = db.query(models.Interface).filter(models.Interface.name == iface_name).first()
    if itf is None or not itf.ip_address:
        return None
    try:
        iface = ipaddress.ip_interface(itf.ip_address)
    except ValueError:
        return None
    if iface.version != 6:
        return None
    # Advertise a /64 (the only prefix length SLAAC supports).
    net = ipaddress.IPv6Network((iface.network.network_address, 64), strict=False)
    return str(net)


def render(db: Session) -> str:
    """Render radvd.conf, or '' when RA is off / no usable IPv6 prefix."""
    cfg = get_config(db)
    if not cfg.enabled or not cfg.interface:
        return ""
    prefix = _iface_v6_prefix(db, cfg.interface)
    if not prefix:
        return ""
    on = lambda b: "on" if b else "off"  # noqa: E731
    lines = [
        "# Generated by MurOS, do not edit by hand.",
        f"interface {cfg.interface} {{",
        "    AdvSendAdvert on;",
        f"    AdvManagedFlag {on(cfg.managed)};",
        f"    AdvOtherConfigFlag {on(cfg.other_config or cfg.advertise_dns)};",
        f"    prefix {prefix} {{",
        "        AdvOnLink on;",
        # Autonomous (SLAAC) unless addresses come from DHCPv6 (managed).
        f"        AdvAutonomous {on(not cfg.managed)};",
        "    };",
    ]
    if cfg.advertise_dns:
        addr = str(ipaddress.ip_interface(
            db.query(models.Interface).filter(models.Interface.name == cfg.interface).first().ip_address
        ).ip)
        lines.append(f"    RDNSS {addr} {{ }};")
    lines.append("};")
    return "\n".join(lines) + "\n"


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=False, capture_output=True)


def apply(db: Session) -> None:
    """Write radvd.conf and start/stop radvd to match the config."""
    conf = render(db)
    if not APPLY:
        return
    if conf:
        MUROS_RADVD_CONF.write_text(conf)
        # radvd requires IPv6 forwarding to advertise as a router.
        _run(["sysctl", "-w", "net.ipv6.conf.all.forwarding=1"])
        _run(["systemctl", "enable", "--now", "radvd.service"])
        _run(["systemctl", "restart", "radvd.service"])
    else:
        _run(["systemctl", "disable", "--now", "radvd.service"])
