# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""Active/passive high availability (HA).

Two firewalls share one (or more) virtual IP (VIP) via VRRP. The active
node is elected on the VRRP priority, the other node stays backup. Active
sessions are synchronized by conntrackd to avoid cutting connections on a
failover.

MurOS relies on two Debian packages: keepalived (VRRP) and conntrackd
(conntrack sync). We generate:
- /etc/keepalived/keepalived.conf
- /etc/conntrackd/conntrackd.conf

Then we (re)start the services. The config naturally survives a reboot
(the systemd services are enabled once and for all, and the config is
re-pushed from the DB by muros_boot.py as a safety net).
"""
from __future__ import annotations

import ipaddress
import os
import subprocess
from pathlib import Path

from app.apply import APPLY_ENABLED

KEEPALIVED_CONF = Path(os.environ.get(
    "MUROS_KEEPALIVED_CONF", "/etc/keepalived/keepalived.conf",
))
CONNTRACKD_CONF = Path(os.environ.get(
    "MUROS_CONNTRACKD_CONF", "/etc/conntrackd/conntrackd.conf",
))
NOTIFY_SCRIPT = Path(os.environ.get(
    "MUROS_HA_NOTIFY", "/usr/lib/muros/ha-notify.sh",
))

# Priorities: primary = 150, secondary = 100. A gap of 50 guarantees the
# primary takes over again when it comes back (unless nopreempt is set).
PRIO_PRIMARY = 150
PRIO_SECONDARY = 100


def _validate_cidr(cidr: str) -> str:
    """Validate and normalize a VIP in IP/prefix format."""
    s = cidr.strip()
    if "/" not in s:
        # Tolerate a bare IP, assume /32.
        ipaddress.ip_address(s)
        return s + "/32"
    iface = ipaddress.ip_interface(s)
    return str(iface)


def _validate_ip(addr: str) -> str:
    ipaddress.ip_address(addr.strip())
    return addr.strip()


def _validate_vrid(vrid: int) -> int:
    if not 1 <= vrid <= 255:
        raise ValueError(f"VRID out of range (1-255): {vrid}")
    return vrid


# --- keepalived.conf generation ---

def render_keepalived(config: dict, vips: list[dict], hostname: str) -> str:
    """Generate the content of /etc/keepalived/keepalived.conf.

    `config` : {role: 'primary'|'secondary', preempt: bool, ...}
    `vips`   : list of {vrid, interface, vip_cidr, auth_pass, description, enabled}
    """
    role = config.get("role", "primary")
    base_prio = PRIO_PRIMARY if role == "primary" else PRIO_SECONDARY
    preempt = config.get("preempt", True)

    lines: list[str] = []
    lines.append("# Generated by MurOS, do not edit by hand")
    lines.append("")
    lines.append("global_defs {")
    lines.append(f"    router_id MUROS-{hostname}")
    lines.append("    enable_script_security")
    lines.append("    script_user root")
    lines.append("}")
    lines.append("")

    for vip in vips:
        if not vip.get("enabled", True):
            continue
        vrid = vip["vrid"]
        iface = vip["interface"]
        cidr = vip["vip_cidr"]
        # The password is truncated to 8 characters by keepalived (auth_type PASS).
        auth = (vip.get("auth_pass") or "muros")[:8]
        prio = vip.get("priority") or base_prio
        desc = vip.get("description") or f"VI_{vrid}"

        lines.append(f"vrrp_instance VI_{vrid} {{")
        lines.append(f"    # {desc}")
        # We force BACKUP everywhere: the election is driven by the priority,
        # which is simpler to reason about than fixed MASTER/BACKUP.
        lines.append("    state BACKUP")
        lines.append(f"    interface {iface}")
        lines.append(f"    virtual_router_id {vrid}")
        lines.append(f"    priority {prio}")
        lines.append("    advert_int 1")
        if not preempt:
            lines.append("    nopreempt")
        lines.append("    authentication {")
        lines.append("        auth_type PASS")
        lines.append(f"        auth_pass {auth}")
        lines.append("    }")
        lines.append("    virtual_ipaddress {")
        lines.append(f"        {cidr}")
        lines.append("    }")
        if NOTIFY_SCRIPT.parent.is_dir() or APPLY_ENABLED:
            lines.append(f'    notify "{NOTIFY_SCRIPT}"')
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


# --- conntrackd.conf generation ---

def render_conntrackd(config: dict, local_addr: str) -> str:
    """Generate the content of /etc/conntrackd/conntrackd.conf.

    `config` : must contain peer_address and sync_interface.
    `local_addr` : local IP on sync_interface (conntrackd listener).
    """
    peer = _validate_ip(config["peer_address"])
    sync_iface = config["sync_interface"].strip()
    local = _validate_ip(local_addr)

    body = f"""# Generated by MurOS, do not edit by hand
Sync {{
    Mode FTFW {{
        ResendQueueSize 131072
        ACKWindowSize 300
        DisableExternalCache Off
    }}
    UDP {{
        IPv4_address {local}
        IPv4_Destination_Address {peer}
        Port 3780
        Interface {sync_iface}
        SndSocketBuffer 1249280
        RcvSocketBuffer 1249280
        Checksum on
    }}
}}

General {{
    Nice -20
    HashSize 32768
    HashLimit 131072
    LogFile off
    Syslog on
    LockFile /var/lock/conntrack.lock
    UNIX {{
        Path /var/run/conntrackd.ctl
        Backlog 20
    }}
    NetlinkBufferSize 2097152
    NetlinkBufferSizeMaxGrowth 8388608
    Filter From Userspace {{
        Protocol Accept {{
            TCP
            UDP
            ICMP
        }}
        Address Ignore {{
            IPv4_address 127.0.0.1
        }}
    }}
}}
"""
    return body


# --- Apply ---

def apply_config(config: dict, vips: list[dict], *,
                 defer_start: bool = False) -> dict:
    """Write the keepalived + conntrackd configs and (re)start the services.

    Returns a dict with dry_run, applied, message.

    defer_start: boot context, avoids the deadlock with
    network-online.target by separating enable / start --no-block.
    """
    import platform
    hostname = platform.node() or "muros"

    # Determine the local IP on the sync interface for conntrackd.
    local_addr = _detect_local_ip(config["sync_interface"])

    ka = render_keepalived(config, vips, hostname)
    cd = render_conntrackd(config, local_addr) if config.get("conntrack_sync", True) else ""

    if not APPLY_ENABLED:
        return {
            "applied": False,
            "dry_run": True,
            "message": (
                f"dry-run: keepalived ({len(ka)} chars) and conntrackd "
                f"({len(cd)} chars) configs prepared but not written (MUROS_APPLY off)."
            ),
        }

    # If HA disabled: stop the services and remove the config files.
    if not config.get("enabled", False):
        _stop_services()
        for p in (KEEPALIVED_CONF, CONNTRACKD_CONF):
            if p.exists():
                p.unlink()
        return {
            "applied": True,
            "dry_run": False,
            "message": "HA disabled, services stopped.",
        }

    KEEPALIVED_CONF.parent.mkdir(parents=True, exist_ok=True)
    KEEPALIVED_CONF.write_text(ka)

    if cd:
        CONNTRACKD_CONF.parent.mkdir(parents=True, exist_ok=True)
        CONNTRACKD_CONF.write_text(cd)

    # Validity tests before restart
    try:
        subprocess.check_output(
            ["keepalived", "-t", "-f", str(KEEPALIVED_CONF)],
            stderr=subprocess.STDOUT, timeout=5,
        )
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            f"keepalived refused the config: {exc.output.decode('utf-8', 'ignore')}"
        ) from exc
    except FileNotFoundError:
        raise RuntimeError("keepalived not installed on this system")

    # Restart conntrackd first (so it is ready when keepalived fails over).
    if cd:
        _restart("conntrackd", defer_start=defer_start)
    _reload_or_restart("keepalived", defer_start=defer_start)

    return {
        "applied": True,
        "dry_run": False,
        "message": "HA applied, keepalived reloaded and conntrackd restarted.",
    }


def _detect_local_ip(iface: str) -> str:
    """Get the first IPv4 attached to the interface."""
    # Guard: empty or whitespace iface -> do not run `ip` on a device ""
    # (otherwise stderr "Device \"\" does not exist." in the journal).
    # We raise a clear message directly.
    iface = (iface or "").strip()
    if not iface:
        raise RuntimeError(
            "sync interface not defined: configure HA from the UI "
            "(High Availability tab) before enabling conntrackd sync."
        )
    try:
        out = subprocess.check_output(
            ["ip", "-o", "-4", "addr", "show", "dev", iface],
            text=True, timeout=3, stderr=subprocess.DEVNULL,
        )
        for line in out.splitlines():
            parts = line.split()
            for i, p in enumerate(parts):
                if p == "inet" and i + 1 < len(parts):
                    return parts[i + 1].split("/")[0]
    except (subprocess.SubprocessError, FileNotFoundError):
        pass
    raise RuntimeError(
        f"no IPv4 found on the sync interface {iface!r}, "
        "cannot generate conntrackd.conf"
    )


def _reload_or_restart(service: str, *, defer_start: bool = False) -> None:
    if defer_start:
        # At boot, we only enable: systemd will start the unit after
        # muros-boot once network-online.target is reached. An explicit
        # reload/restart here brings nothing and could cause a double
        # startup.
        _restart(service, defer_start=True)
        return
    try:
        subprocess.check_call(["systemctl", "reload", service], timeout=10)
    except (subprocess.SubprocessError, FileNotFoundError):
        _restart(service)


def _restart(service: str, *, defer_start: bool = False) -> None:
    try:
        # enable (without --now): persistence, does not touch the runtime,
        # depends on no target -> safe in boot context.
        subprocess.check_call(["systemctl", "enable", service], timeout=5)
        if defer_start:
            # In boot context, --no-block enqueues the restart: the command
            # returns immediately, systemd will run the startup after
            # muros-boot. Without --no-block, we wait on
            # network-online.target which waits on muros-boot -> deadlock.
            subprocess.check_call(
                ["systemctl", "--no-block", "restart", service], timeout=5,
            )
        else:
            subprocess.check_call(["systemctl", "restart", service], timeout=15)
    except (subprocess.SubprocessError, FileNotFoundError):
        pass


def _stop_services() -> None:
    for svc in ("keepalived", "conntrackd"):
        try:
            subprocess.check_call(["systemctl", "disable", "--now", svc], timeout=15)
        except (subprocess.SubprocessError, FileNotFoundError):
            pass


# --- Debian package installation ---

def install_packages() -> dict:
    """Install the packages needed for HA via apt.

    Idempotent: if keepalived and conntrackd are already there, does
    nothing. Refuses to run if MurOS is not running as root, or if apt is
    not available (dev box on another OS).

    Returns a dict with:
      - installed (bool) : True if the operation succeeded
      - already_present (list[str]) : packages already installed before the call
      - newly_installed (list[str]) : freshly installed packages
      - output_tail (str) : last characters of the apt output (for debug)
    """
    pkgs = ["keepalived", "conntrackd"]
    already = [p for p in pkgs if _which(p)]
    missing = [p for p in pkgs if p not in already]

    if not missing:
        return {
            "installed": True,
            "already_present": already,
            "newly_installed": [],
            "output_tail": "",
        }

    if not APPLY_ENABLED:
        return {
            "installed": False,
            "already_present": already,
            "newly_installed": [],
            "output_tail": (
                f"dry-run: would have run 'apt-get install -y {' '.join(missing)}' "
                "(MUROS_APPLY off)."
            ),
        }

    if os.geteuid() != 0:
        raise RuntimeError(
            "Package installation impossible: MurOS must run as root "
            "to use apt-get. Start the service as root or "
            "install the packages manually: "
            f"apt install -y {' '.join(missing)}"
        )

    try:
        subprocess.check_call(
            ["which", "apt-get"], stdout=subprocess.DEVNULL, timeout=2,
        )
    except (subprocess.SubprocessError, FileNotFoundError) as exc:
        raise RuntimeError(
            "apt-get not found on this system. Automatic installation "
            "is only supported on Debian/Ubuntu."
        ) from exc

    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive", "LC_ALL": "C"}

    # apt-get update first, otherwise installation may fail on a stale cache.
    proc_update = subprocess.run(
        ["apt-get", "update", "-q"],
        env=env, capture_output=True, text=True, timeout=120,
    )
    if proc_update.returncode != 0:
        raise RuntimeError(
            f"apt-get update failed (code {proc_update.returncode}): "
            f"{(proc_update.stderr or '').strip()[:400]}"
        )

    proc = subprocess.run(
        ["apt-get", "install", "-y", "--no-install-recommends", *missing],
        env=env, capture_output=True, text=True, timeout=600,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"apt-get install failed (code {proc.returncode}): "
            f"{(proc.stderr or '').strip()[:400]}"
        )

    # Verify it is really there now.
    still_missing = [p for p in missing if not _which(p)]
    if still_missing:
        raise RuntimeError(
            f"Packages still missing after install: {', '.join(still_missing)}. "
            f"apt output: {proc.stdout[-400:]}"
        )

    return {
        "installed": True,
        "already_present": already,
        "newly_installed": missing,
        "output_tail": proc.stdout[-800:],
    }


# --- Status (read-only) ---

def _keepalived_version() -> str | None:
    from app.service_state import pkg_version
    return pkg_version("keepalived")


def _conntrackd_version() -> str | None:
    from app.service_state import pkg_version
    return pkg_version("conntrackd")


def get_status() -> dict:
    """Live HA state: services + VRRP role + conntrackd stats."""
    from app.service_state import service_state as _state
    return {
        "keepalived_active": _systemd_active("keepalived"),
        "conntrackd_active": _systemd_active("conntrackd"),
        "keepalived_state": _state("keepalived.service"),
        "conntrackd_state": _state("conntrackd.service"),
        "keepalived_installed": _which("keepalived"),
        "conntrackd_installed": _which("conntrackd"),
        "keepalived_version": _keepalived_version(),
        "conntrackd_version": _conntrackd_version(),
        "vrrp_instances": _read_vrrp_state(),
        "conntrack_stats": _read_conntrackd_stats(),
    }


from app.service_state import is_active as _systemd_active, which as _which  # noqa: E402


def _read_vrrp_state() -> list[dict]:
    """keepalived can dump its state by sending SIGUSR1 (creates /tmp/keepalived.data).
    We avoid sending a signal on every request and parse the journal instead.
    Fallback: we look at which VIPs are attached to the kernel via `ip -4 addr`.
    """
    state: list[dict] = []
    try:
        out = subprocess.check_output(
            ["journalctl", "-u", "keepalived", "-n", "50", "--no-pager", "-o", "cat"],
            text=True, timeout=5,
        )
    except (subprocess.SubprocessError, FileNotFoundError):
        return state

    # Parse the "Entering MASTER STATE" / "Entering BACKUP STATE" / "Entering FAULT STATE"
    # transitions per VI_<vrid> instance.
    last: dict[str, str] = {}
    for line in out.splitlines():
        if "Entering" not in line:
            continue
        # e.g. "(VI_50) Entering MASTER STATE"
        m_state = None
        if "MASTER STATE" in line:
            m_state = "MASTER"
        elif "BACKUP STATE" in line:
            m_state = "BACKUP"
        elif "FAULT STATE" in line:
            m_state = "FAULT"
        if not m_state:
            continue
        if "(" in line and ")" in line:
            name = line.split("(", 1)[1].split(")", 1)[0]
            last[name] = m_state

    for name, st in last.items():
        state.append({"name": name, "state": st})
    return state


def _read_conntrackd_stats() -> dict:
    """Read `conntrackd -s` to expose the sync counters."""
    if not _which("conntrackd"):
        return {}
    try:
        out = subprocess.check_output(
            ["conntrackd", "-s"], text=True, timeout=3, stderr=subprocess.STDOUT,
        )
    except (subprocess.SubprocessError, FileNotFoundError):
        return {}
    stats: dict = {}
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("current active connections:"):
            stats["active"] = _to_int(line.split(":", 1)[1])
        elif line.startswith("connections created:"):
            stats["created"] = _to_int(line.split(":", 1)[1].split()[0])
        elif line.startswith("connections updated:"):
            stats["updated"] = _to_int(line.split(":", 1)[1].split()[0])
        elif line.startswith("connections destroyed:"):
            stats["destroyed"] = _to_int(line.split(":", 1)[1].split()[0])
    return stats


def _to_int(s: str) -> int:
    try:
        return int(s.strip())
    except (ValueError, TypeError):
        return 0
