"""Nginx configuration for the MurOS site driven from the UI (listen address, ports).

At deploy time, /etc/nginx/sites-available/muros is written with a static
config (packaging template). When the admin changes the listener from the
UI (HTTP Access page), this file is regenerated with the new parameters
(listen_address, port_https, port_http).

Validated with nginx -t before reload, rolled back if invalid.
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path

from app.apply import APPLY_ENABLED

log = logging.getLogger("muros.nginx")

SITE_CONF = Path("/etc/nginx/sites-available/muros")
SITE_CONF_BAK = Path("/etc/nginx/sites-available/muros.muros-bak")


def _server_block(listen_lines: list[str], tls: bool) -> list[str]:
    """Shared server block, in HTTP or HTTPS."""
    block = ["server {"]
    for line in listen_lines:
        block.append(f"    {line}")
    block.extend([
        "    server_name _;",
        "",
    ])
    if tls:
        block.extend([
            "    ssl_certificate     /etc/nginx/ssl/muros.crt;",
            "    ssl_certificate_key /etc/nginx/ssl/muros.key;",
            "    ssl_protocols       TLSv1.2 TLSv1.3;",
            "    ssl_ciphers         HIGH:!aNULL:!MD5;",
            "    ssl_prefer_server_ciphers on;",
            "    ssl_session_cache   shared:SSL:10m;",
            "    ssl_session_timeout 1d;",
            "    add_header Strict-Transport-Security \"max-age=31536000\" always;",
            "",
        ])
    block.extend([
        "    error_page 502 503 504 /muros-503.html;",
        "    location = /muros-503.html { root /etc/nginx/html; internal; }",
        "",
        "    add_header X-Frame-Options DENY always;",
        "    add_header X-Content-Type-Options nosniff always;",
        "    add_header Referrer-Policy strict-origin-when-cross-origin always;",
        # Content-Security-Policy: lock the SPA to its own origin. Everything is
        # served from 'self' (no web fonts, no CDN). 'unsafe-inline' is required
        # for style only (React inline styles + the QR SVGs injected via
        # dangerouslySetInnerHTML); scripts stay 'self' (no inline JS, no eval in
        # the Vite build).
        "    add_header Content-Security-Policy \""
        "default-src 'self'; "
        "base-uri 'self'; "
        "frame-ancestors 'none'; "
        "object-src 'none'; "
        "script-src 'self'; "
        "style-src 'self' 'unsafe-inline'; "
        "font-src 'self'; "
        "img-src 'self' data:; "
        "connect-src 'self'; "
        "form-action 'self'\" always;",
        "    add_header Permissions-Policy "
        "\"geolocation=(), microphone=(), camera=(), payment=(), usb=()\" always;",
        "",
        "    client_max_body_size 100M;",
        "    root /opt/muros/web;",
        "    index index.html;",
        "",
        "    location /api/ {",
        "        proxy_pass         http://127.0.0.1:8000;",
        "        proxy_http_version 1.1;",
        "        proxy_set_header   Host              $host;",
        "        proxy_set_header   X-Real-IP         $remote_addr;",
        "        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;",
        "        proxy_set_header   X-Forwarded-Proto $scheme;",
        "        proxy_read_timeout 300s;",
        "        proxy_send_timeout 300s;",
        "    }",
        "",
        "    location / { try_files $uri $uri/ /index.html; }",
        "",
        "    location ~* \\.(js|css|woff2?|ttf|otf|svg|png|jpg|jpeg|gif|ico|webp)$ {",
        "        expires 1y;",
        "        add_header Cache-Control \"public, immutable\";",
        "    }",
        "}",
        "",
    ])
    return block


def render_site_conf(cfg) -> str:
    """Generate the full sites-available/muros content.

    HTTPS is always on (snakeoil cert by default, real cert uploaded from
    the UI). HTTP redirects to HTTPS unless the admin explicitly disables it.
    """
    listen = (cfg.listen_address or "0.0.0.0").strip()
    port_https = int(cfg.port_https or 443)
    port_http = int(cfg.port_http or 80)
    redirect = bool(getattr(cfg, "redirect_http_to_https", True))

    if listen == "0.0.0.0" or not listen:
        http_listen = [
            f"listen {port_http} default_server;",
            f"listen [::]:{port_http} default_server;",
        ]
        https_listen = [
            f"listen {port_https} ssl default_server;",
            f"listen [::]:{port_https} ssl default_server;",
            "http2 on;",
        ]
    else:
        http_listen = [f"listen {listen}:{port_http};"]
        https_listen = [
            f"listen {listen}:{port_https} ssl;",
            "http2 on;",
        ]

    parts: list[str] = [
        "# Generated by MurOS - do not edit by hand.",
        "# Edit from the UI -> HTTP Access.",
        "",
    ]

    if redirect:
        parts.extend([
            "server {",
            *(f"    {line}" for line in http_listen),
            "    server_name _;",
            "    return 301 https://$host$request_uri;",
            "}",
            "",
        ])
    else:
        # HTTP also serves the UI (explicit degraded mode)
        parts.extend(_server_block(http_listen, tls=False))

    parts.extend(_server_block(https_listen, tls=True))

    return "\n".join(parts)


def apply_config(cfg) -> dict:
    """Write sites-available/muros and reload nginx with rollback."""
    if not APPLY_ENABLED:
        return {
            "applied": False,
            "message": "dry-run: MUROS_APPLY off.",
            "preview": render_site_conf(cfg),
        }
    if os.geteuid() != 0:
        raise RuntimeError("Cannot modify nginx: MurOS must run as root.")

    # Backup before writing, for rollback.
    if SITE_CONF.exists():
        shutil.copy2(SITE_CONF, SITE_CONF_BAK)

    SITE_CONF.parent.mkdir(parents=True, exist_ok=True)
    SITE_CONF.write_text(render_site_conf(cfg), encoding="utf-8")
    os.chmod(SITE_CONF, 0o644)

    # nginx -t to validate
    check = subprocess.run(
        ["nginx", "-t"], capture_output=True, text=True, timeout=10,
    )
    if check.returncode != 0:
        # Rollback
        if SITE_CONF_BAK.exists():
            shutil.copy2(SITE_CONF_BAK, SITE_CONF)
        raise RuntimeError(
            f"nginx -t rejected the config: {check.stderr.strip()[:400]}"
        )

    # Reload
    r = subprocess.run(
        ["systemctl", "reload", "nginx.service"],
        capture_output=True, text=True, timeout=15,
    )
    if r.returncode != 0:
        log.warning("systemctl reload nginx : %s", r.stderr)

    if SITE_CONF_BAK.exists():
        SITE_CONF_BAK.unlink()

    listen_disp = cfg.listen_address or "0.0.0.0"
    return {
        "applied": True,
        "message": f"Nginx reconfigured (HTTPS on {listen_disp}:{cfg.port_https}). "
                   "Check UI access before closing this page.",
    }
