# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""NTP configuration through chrony.

MurOS uses chrony as its NTP daemon (enabled by default at install).
chrony is more capable than systemd-timesyncd: it can act as an NTP
server for the LAN, has finer step/slew control and exposes a rich
introspection interface via chronyc.

Reading:
- ``timedatectl show`` : sync state (NTP=, NTPSynchronized=, Timezone=).
  These come from the kernel and are populated by any running NTP
  daemon, chrony included.
- ``chronyc tracking`` : active reference source and stratum.

Writing:
- MurOS drops /etc/chrony/conf.d/muros.conf containing only ``server``
  lines. Debian's stock /etc/chrony/chrony.conf includes conf.d, so the
  rest of the chrony configuration stays intact.
- After writing: ``systemctl restart chrony`` (chronyd on some distros).
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

MUROS_CHRONY_CONF = Path(os.environ.get(
    "MUROS_CHRONY_CONF", "/etc/chrony/conf.d/muros.conf",
))

DEFAULT_SERVERS = [
    "0.debian.pool.ntp.org",
    "1.debian.pool.ntp.org",
    "2.debian.pool.ntp.org",
    "3.debian.pool.ntp.org",
]


from app.service_state import which as _which  # noqa: E402


def _chrony_unit() -> str:
    """Return the systemd unit name for chrony on this distribution.

    Debian/Ubuntu ship 'chrony.service'; some distros use 'chronyd'.
    """
    return "chrony"


def get_backend() -> str:
    """Return 'chrony' when chrony is available, else 'none'."""
    if _which("chronyc") or _which("chronyd"):
        return "chrony"
    return "none"


def _timedatectl_info() -> dict:
    info: dict = {}
    try:
        td = subprocess.check_output(["timedatectl", "show"], text=True, timeout=5)
    except (subprocess.SubprocessError, FileNotFoundError):
        return info
    for line in td.splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            info[k.strip()] = v.strip()
    return info


def _chrony_tracking() -> dict:
    """Parse `chronyc tracking` into a dict (reference name, stratum)."""
    out: dict = {}
    try:
        raw = subprocess.check_output(["chronyc", "tracking"], text=True, timeout=5)
    except (subprocess.SubprocessError, FileNotFoundError):
        return out
    for line in raw.splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        out[k.strip()] = v.strip()
    return out


def get_status() -> dict:
    """State of the chrony synchronization."""
    if get_backend() != "chrony":
        return {"available": False, "backend": "none"}

    info = _timedatectl_info()
    tracking = _chrony_tracking()

    # Reference name : 'Reference ID' line looks like
    # '192.168.1.1 (ntp.example.org)' or 'A29FC87B (time.cloudflare.com)'.
    ref_name = ""
    ref_id = tracking.get("Reference ID", "")
    if "(" in ref_id and ")" in ref_id:
        ref_name = ref_id[ref_id.find("(") + 1:ref_id.find(")")]
    elif ref_id:
        ref_name = ref_id.split()[0]

    stratum = 0
    try:
        stratum = int(tracking.get("Stratum", "0") or 0)
    except ValueError:
        stratum = 0

    ntp_active = info.get("NTP") == "yes"
    synced = info.get("NTPSynchronized") == "yes"
    if synced:
        leap = "Normal"
    elif ntp_active:
        leap = "Synchronizing"
    else:
        leap = "NTP service inactive"
    return {
        "available": True,
        "backend": "chrony",
        "ref_name": ref_name,
        "stratum": stratum,
        "leap_status": leap,
        "ntp_synchronized": synced,
        "ntp_active": ntp_active,
        "timezone": info.get("Timezone", ""),
    }


def get_servers() -> list[str]:
    """Read the current server list from the MurOS chrony drop-in."""
    if not MUROS_CHRONY_CONF.is_file():
        return list(DEFAULT_SERVERS)
    servers: list[str] = []
    for line in MUROS_CHRONY_CONF.read_text().splitlines():
        s = line.strip()
        if s.startswith("server "):
            parts = s.split()
            if len(parts) >= 2:
                servers.append(parts[1])
    return servers or list(DEFAULT_SERVERS)


def get_config_path() -> str:
    return str(MUROS_CHRONY_CONF)


def set_servers(servers: list[str]) -> None:
    """Write the chrony drop-in and restart the service."""
    cleaned = [s.strip() for s in servers if s.strip()]
    if not cleaned:
        raise ValueError("at least one NTP server is required")
    if get_backend() != "chrony":
        raise RuntimeError(
            "chrony is not available on this system (chronyc / chronyd missing)."
        )
    MUROS_CHRONY_CONF.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by MurOS, do not edit by hand."]
    lines += [f"server {host} iburst" for host in cleaned]
    MUROS_CHRONY_CONF.write_text("\n".join(lines) + "\n")
    _restart(_chrony_unit())


def _restart(service: str) -> None:
    try:
        subprocess.check_call(["systemctl", "restart", service], timeout=10)
    except (subprocess.SubprocessError, FileNotFoundError):
        # Silent : in dev (MUROS_APPLY off) there is no systemctl / no rights.
        pass
