# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 MurOS contributors.
"""Remote syslog forwarding: ship every log line to a central collector.

MurOS logs to journald. We drive the standard Debian rsyslog daemon,
which reads the journal via imjournal and forwards everything to a remote
syslog server / SIEM through an omfwd action. No custom protocol: plain
RFC5424 (or legacy RFC3164) over UDP or TCP, which every collector
(rsyslog, syslog-ng, Graylog, Splunk, Wazuh, ...) understands.

The rendered drop-in lives in /etc/rsyslog.d/muros-remote.conf. rsyslog
loads /etc/rsyslog.d/*.conf out of the box (no main-file edit needed,
unlike snmpd). An apply restarts rsyslog. When disabled, the drop-in is
removed so forwarding stops on the next apply.

Every side effect respects MUROS_APPLY: in dry-run nothing is executed.
"""
from __future__ import annotations

import logging
import os
import re
import subprocess
from pathlib import Path

from app.apply import APPLY_ENABLED
from app.service_state import which as _which

log = logging.getLogger("muros.syslog")

SYSLOG_PACKAGES = ["rsyslog"]
SYSLOG_SERVICE = "rsyslog"
SYSLOG_CONF = Path("/etc/rsyslog.d/muros-remote.conf")

# RFC5424 (structured) vs RFC3164 (legacy BSD) rsyslog templates.
_TEMPLATES = {
    "rfc5424": "RSYSLOG_SyslogProtocol23Format",
    "rfc3164": "RSYSLOG_TraditionalForwardFormat",
}
_HOST_RE = re.compile(r"^[A-Za-z0-9._:-]{1,255}$")


def validate_config(host: str, port: int, protocol: str, fmt: str) -> None:
    if not host or not _HOST_RE.match(host):
        raise ValueError("host must be a valid IP address or hostname")
    if not (1 <= port <= 65535):
        raise ValueError("port must be between 1 and 65535")
    if protocol not in ("udp", "tcp"):
        raise ValueError("protocol must be udp or tcp")
    if fmt not in _TEMPLATES:
        raise ValueError("format must be rfc5424 or rfc3164")


def get_status() -> dict:
    """Live status: rsyslog installed, service state, version."""
    from app.service_state import service_state as _state, is_active, pkg_version
    installed = _which("rsyslogd")
    return {
        "installed": installed,
        "service_active": is_active(SYSLOG_SERVICE),
        "service_state": _state(SYSLOG_SERVICE),
        "version": pkg_version("rsyslog"),
    }


def install_packages() -> dict:
    """Install rsyslog via apt (mirrors the SNMP install flow)."""
    if _which("rsyslogd"):
        return {"installed": True, "already_present": SYSLOG_PACKAGES,
                "newly_installed": [], "output_tail": ""}
    if not APPLY_ENABLED:
        return {"installed": False, "already_present": [], "newly_installed": [],
                "output_tail": ("dry-run: would run 'apt-get install -y "
                                f"{' '.join(SYSLOG_PACKAGES)}' (MUROS_APPLY off).")}
    if os.geteuid() != 0:
        raise RuntimeError(
            "Install requires root. Run manually: "
            f"apt install -y {' '.join(SYSLOG_PACKAGES)}"
        )
    try:
        subprocess.check_call(["which", "apt-get"], stdout=subprocess.DEVNULL, timeout=2)
    except (subprocess.SubprocessError, FileNotFoundError) as exc:
        raise RuntimeError("apt-get not found, only supported on Debian/Ubuntu.") from exc
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive", "LC_ALL": "C"}
    up = subprocess.run(["apt-get", "update", "-q"], env=env,
                        capture_output=True, text=True, timeout=120)
    if up.returncode != 0:
        raise RuntimeError(f"apt-get update failed: {(up.stderr or '').strip()[:400]}")
    proc = subprocess.run(
        ["apt-get", "install", "-y", "--no-install-recommends", *SYSLOG_PACKAGES],
        env=env, capture_output=True, text=True, timeout=600,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"apt-get install failed (code {proc.returncode}): "
            f"{(proc.stderr or '').strip()[:400]}"
        )
    if not _which("rsyslogd"):
        raise RuntimeError(f"rsyslogd missing after install. Output: {proc.stdout[-400:]}")
    return {"installed": True, "already_present": [], "newly_installed": SYSLOG_PACKAGES,
            "output_tail": proc.stdout[-800:]}


def render_conf(cfg) -> str:
    """Render /etc/rsyslog.d/muros-remote.conf (omfwd forward rule).

    A disk queue with infinite retry keeps logs buffered when the
    collector is briefly unreachable, instead of dropping them.
    """
    template = _TEMPLATES.get(cfg.format, _TEMPLATES["rfc5424"])
    return (
        "# Generated by MurOS - do not edit by hand.\n"
        "# Forwards every journald/syslog message to a remote collector.\n"
        "*.* action(type=\"omfwd\"\n"
        f"    target=\"{cfg.host}\"\n"
        f"    port=\"{cfg.port}\"\n"
        f"    protocol=\"{cfg.protocol}\"\n"
        f"    template=\"{template}\"\n"
        "    action.resumeRetryCount=\"-1\"\n"
        "    queue.type=\"LinkedList\"\n"
        "    queue.saveOnShutdown=\"on\")\n"
    )


def write_conf(cfg) -> dict:
    """Materialise the drop-in only (no systemd action).

    When disabled, remove the drop-in so a later apply stops forwarding.
    """
    if not cfg.enabled:
        if APPLY_ENABLED and SYSLOG_CONF.exists():
            SYSLOG_CONF.unlink()
        return {"message": "Syslog forwarding saved (disabled).", "service": SYSLOG_SERVICE}
    validate_config(cfg.host, cfg.port, cfg.protocol, cfg.format)
    text = render_conf(cfg)
    if not APPLY_ENABLED:
        return {"message": f"dry-run: would write {SYSLOG_CONF} ({len(text)} bytes).",
                "service": SYSLOG_SERVICE, "conf_preview": text}
    if not _which("rsyslogd"):
        raise RuntimeError("rsyslogd not found. Click 'Install now' first.")
    SYSLOG_CONF.parent.mkdir(parents=True, exist_ok=True)
    SYSLOG_CONF.write_text(text, encoding="utf-8")
    os.chmod(SYSLOG_CONF, 0o644)
    return {"message": f"Forwarding to {cfg.host}:{cfg.port}/{cfg.protocol} saved.",
            "service": SYSLOG_SERVICE}


def reload(cfg) -> dict:
    """Restart rsyslog to pick up the on-disk drop-in (explicit Apply)."""
    if not APPLY_ENABLED:
        return {"message": "dry-run: reload skipped.", "service": SYSLOG_SERVICE}
    if not cfg.enabled:
        # Forwarding off: rsyslog stays running for local logging, we just
        # restart it so the removed drop-in takes effect.
        subprocess.run(["systemctl", "restart", SYSLOG_SERVICE],
                       capture_output=True, timeout=15)
        return {"message": "Syslog forwarding stopped.", "service": SYSLOG_SERVICE}
    subprocess.run(["systemctl", "enable", "--now", SYSLOG_SERVICE],
                   capture_output=True, timeout=15)
    r = subprocess.run(["systemctl", "restart", SYSLOG_SERVICE],
                       capture_output=True, text=True, timeout=15)
    if r.returncode != 0:
        raise RuntimeError(f"Restart {SYSLOG_SERVICE} failed: {(r.stderr or '').strip()[:400]}")
    return {"message": f"rsyslog forwarding to {cfg.host}:{cfg.port}.",
            "service": SYSLOG_SERVICE}
