#!/bin/sh
# Applique la conf unattended-upgrades de MurOS.
# Lit /etc/muros/unattended.json si present, sinon utilise un defaut
# simple : Lun-Jeu 03:00 pour tout le monde. Si HA et l'admin veut
# decorreler les upgrades, il le fait via l'UI (System > Updates > Edit).
#
# Ecrit le drop-in systemd, fait daemon-reload, enable/disable le timer
# selon le champ enabled. Idempotent.
#
# Appele par :
#   - debian/postinst (premiere install + upgrade muros)
#   - backend FastAPI sur PUT /api/updates/unattended
set -e

CONF=/etc/muros/unattended.json
DROPIN_DIR=/etc/systemd/system/apt-daily-upgrade.timer.d
DROPIN=$DROPIN_DIR/muros-schedule.conf

DEFAULT_HOUR=3
DEFAULT_MINUTE=0
DEFAULT_DAYS="Mon,Tue,Wed,Thu"

if [ -f "$CONF" ]; then
  ENABLED=$(python3 -c 'import json,sys; print("true" if json.load(open("'"$CONF"'")).get("enabled", True) else "false")')
  DAYS=$(python3 -c 'import json; print(",".join(json.load(open("'"$CONF"'")).get("days") or []))')
  HOUR=$(python3 -c 'import json; print(json.load(open("'"$CONF"'")).get("hour", '"$DEFAULT_HOUR"'))')
  MINUTE=$(python3 -c 'import json; print(json.load(open("'"$CONF"'")).get("minute", '"$DEFAULT_MINUTE"'))')
else
  ENABLED=true
  DAYS=$DEFAULT_DAYS
  HOUR=$DEFAULT_HOUR
  MINUTE=$DEFAULT_MINUTE
fi

# Fallbacks defensifs en cas de conf incoherente.
[ -z "$DAYS" ] && DAYS=$DEFAULT_DAYS
printf '%d' "$HOUR" >/dev/null 2>&1 || HOUR=$DEFAULT_HOUR
printf '%d' "$MINUTE" >/dev/null 2>&1 || MINUTE=$DEFAULT_MINUTE

install -d -m 755 "$DROPIN_DIR"
cat > "$DROPIN" <<DROP
# Generated by /usr/lib/muros/apply-unattended.sh. Source of truth :
# /etc/muros/unattended.json (managed by the MurOS UI). Manual edits
# here are overwritten on the next muros upgrade or UI save.
[Timer]
OnCalendar=
OnCalendar=${DAYS} $(printf '%02d:%02d' "$HOUR" "$MINUTE")
RandomizedDelaySec=1h
Persistent=true
DROP

systemctl daemon-reload 2>/dev/null || true
if [ "$ENABLED" = "true" ]; then
  systemctl enable --now apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
else
  systemctl disable --now apt-daily-upgrade.timer 2>/dev/null || true
  # On laisse apt-daily.timer (refresh des listes) actif pour que la
  # detection des MAJ disponibles continue de fonctionner.
fi
